
# Auth0 Lock
target 'SogetiTrainingCamp' do
    pod 'Lock', '~> 1.26'
    pod 'Lock/TouchID'
    pod 'Lock/SMS'
    pod 'Lock/Email'
end

target 'SogetiTrainingCampTests' do
    pod 'Lock', '~> 1.26'
    pod 'Lock/TouchID'
    pod 'Lock/SMS'
    pod 'Lock/Email'
end